Repository agential-ai/agential, pull requests merged in 2024-03, with the labels that each got.

#53 Updating Contribution.md
  CONTRIBUTING.md
Labels: documentation, good first issue

#24 ExpeL
  README.md
  discussion_agents/cog/agent/base.py
  discussion_agents/cog/agent/expel.py
  discussion_agents/cog/agent/reflexion.py
  discussion_agents/cog/functional/expel.py
  discussion_agents/cog/functional/react.py
  discussion_agents/cog/functional/reflexion.py
  discussion_agents/cog/modules/memory/base.py
  discussion_agents/cog/modules/memory/expel.py
  discussion_agents/cog/prompts/expel.py
  discussion_agents/cog/prompts/react.py
  discussion_agents/cog/prompts/reflexion.py
  discussion_agents/cog/train/__init__.py
  discussion_agents/utils/general.py
  tests/assets/.gitkeep
  tests/assets/expel/__init__.py
  tests/assets/expel/expel_experiences_10_fake.joblib
  tests/assets/hotpotqa/__init__.py
  tests/assets/hotpotqa/hotpot-qa-distractor-sample.joblib
  tests/cog/agent/test_expel.py
  tests/cog/agent/test_reflexion.py
  tests/cog/functional/test_expel_functional.py
  tests/cog/functional/test_react_functional.py
  tests/cog/functional/test_reflexion_functional.py
  tests/cog/modules/memory/test_expel_memory.py
  tests/conftest.py
  tests/fixtures/agent.py
  tests/fixtures/data.py
  tests/fixtures/retriever.py
  tests/utils/test_general.py
Labels: enhancement

#39 FEVER for ReAct
  README.md
  discussion_agents/cog/agent/expel.py
  discussion_agents/cog/agent/react.py
  discussion_agents/cog/agent/reflexion.py
  discussion_agents/cog/functional/expel.py
  discussion_agents/cog/functional/generative_agents.py
  discussion_agents/cog/functional/react.py
  discussion_agents/cog/prompts/react.py
  test_environment.py
  tests/cog/agent/test_react.py
  tests/cog/functional/test_react_functional.py
  tests/cog/functional/test_reflexion_functional.py
  tests/cog/modules/memory/test_expel_memory.py
Labels: enhancement, good first issue
