Repository agential-ai/agential, pull requests merged in 2024-02, with the labels that each got.

#26 First Update README.md
  README.md
Labels: documentation

#30 fixed small bugs with multiple trials
  discussion_agents/cog/agent/reflexion.py
  discussion_agents/cog/modules/reflect/reflexion.py
Labels: bug

#34 Fixed reset for ReflexionReAct
  discussion_agents/cog/agent/reflexion.py
Labels: bug

#31 Update README.md
  README.md
Labels: documentation, good first issue

#36 Update README.md (repo structure, features)
  .gitignore
  README.md
  notebooks/3.0-vt-test-langchain-gen-agents.ipynb
  notebooks/7.0-vt-test-imports.ipynb
Labels: documentation, good first issue

#38 Add new file contribution.md
  CONTRIBUTING.md
Labels: documentation, good first issue

#32 Comprehensive Unit Tests for ReAct and Reflexion
  discussion_agents/cog/agent/reflexion.py
  discussion_agents/cog/functional/react.py
  tests/cog/agent/test_react.py
  tests/cog/agent/test_reflexion.py
  tests/cog/functional/test_react_functional.py
  tests/cog/functional/test_reflexion_functional.py
  tests/cog/modules/reflect/test_reflexion_reflect.py
Labels: help wanted, good first issue

#43 Add Developer Setup & Pre-commit to CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation
