Repository agential-ai/agential, pull requests merged in 2024-07, with the labels that each got.

#183 Structured Outputs with Pydantic for CRITIC (QA, Math, Code)
  agential/cog/agent/critic.py
  agential/cog/strategies/critic/base.py
Labels: enhancement, design

#196 Let's get this done
  agential/cog/prompts/benchmark/ambignq.py
  agential/cog/prompts/benchmark/gsm8k.py
  agential/cog/prompts/benchmark/hotpotqa.py
  agential/cog/prompts/benchmark/svamp.py
  agential/cog/prompts/benchmark/triviaqa.py
Labels: enhancement, design

#197 Structured Outputs for ReAct with Pydantic
  agential/cog/agent/react.py
  agential/cog/strategies/react/base.py
Labels: design

#202 NO MORE FEWSHOT EXAMPLES PLEASEEEEEEEE
  agential/cog/prompts/agent/reflexion.py
Labels: enhancement
